local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("PetsCMID") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Aquatic Pets\\Dali")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Aquatic Pets\\Gloom Toad")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Aquatic Pets\\Linda the Lucky")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Aquatic Pets\\Mud Potadpole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Aquatic Pets\\Percival")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Aquatic Pets\\Zone Pets\\Waddles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Blistercreepling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Devouring Runt")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Achievement Pets\\Do, Child of Filo")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Ebon Snapling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Flicker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Hexed Bunny")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Pangolil")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Rootling Nester")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Sootpaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Striped Snakebiter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Swamp Biter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Beast Pets\\Willie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Critter Pets\\Amber Treeflitter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Critter Pets\\Naloki")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Critter Pets\\Scruffbeak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Critter Pets\\Silkcrawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Critter Pets\\Violet Chick")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Dragonkin Pets\\Sunwing Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Elemental Pets\\Voldy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Flying Pets\\Akil Fledgling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Flying Pets\\Azure Sporebat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Flying Pets\\Dragonhawk Mosswing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Flying Pets\\Emberwing Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Vendor Pets\\Lil' Preyseeker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Nether Familiar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Riftblade Familiar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Silvermoon Broom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Companion Pets\\Magic Pets\\Vibrant Manaling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Voidcrawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Wrathful Wyrm")
