local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("AchievementsCTWW") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Biblo Archivist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\War Within\\Explore K'aresh")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Khaz Algar Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\K'aresh Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\The Missing Lynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Khaz Algar Safari")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Lost and Found")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Secrets of the K'areshi")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within\\Exploration\\Treasures of K'aresh")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Events\\Two Minutes to Midnight")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\TWW Raids\\Glory of the Nerub-ar Raider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Loremaster of Khaz Algar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\The Isle of Dorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\The Ringing Deeps")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Hallowfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Azj-Kahet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Isle of Dorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of The Ringing Deeps")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Hallowfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Azj-Kahet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\You Xal Not Pass")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of the Isle of Dorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of the Isle of Dorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Flat Earthen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\We're Here All Night")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Star of Dorn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Rocked to Sleep")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of The Ringing Deeps")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of The Ringing Deeps")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\It's Not Much, But It's Honest Work")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Notable Machines")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\To All the Slimes I Love")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Super Size Snuffling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Not So Quick Fix")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of Hallowfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of Hallowfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Mereldar Menace")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Beacon of Hope")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Igniting the Keyflames")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Sharing the Light")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Children's Entertainer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of Azj-Kahet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of Azj-Kahet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\You Can't Hang With Us")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\The Unseeming")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Worm Theory")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Itsy Bitsy Spider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Smelling History")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Bookworm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Song of Secrets")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Siren-ity Now!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Excavation Projects")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Clean Up on Isle Siren")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of the Storm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Choir of Citrines")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Slate of the Union")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Rage Aside the Machine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Isle Remember You")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Crystal Chronicled")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Azj the World Turns")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Leave No Treasure Unfound")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Dread Pit Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Waterworkds Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Fungal Folly Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Kriegval's Rest Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Mycomancer Cavern Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Nightfall Sanctum Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Skittering Breach Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Sinkhole Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Tak-Rethan Abyss Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Spiral Weave Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Excavation Site 9 Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Sidestreet Sluice Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Underkeep Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Earthcrawl Mines Discoveries")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\One Rank Higher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Two Ranks Higher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Three Ranks Higher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Best In Class")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\Fate of the Kirin Tor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delve Beyond")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delve Infinite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delver's Dirigible Recovery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\Read Between the Lines")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Family Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Aquatic Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Beast Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Critter Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Dragonkin Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Elemental Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Flying Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Humanoid Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Magic Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Mechanical Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Undead Battler of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\A Good Day to Dye Hard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Key to Madness")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Reputation\\War Within\\In with the Cartels")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Glory of the Delver")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Sporesweeper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Just Keep Swimming")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Spider Senses")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Daystormer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Brann Development")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\My First Nemesis")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\My New Nemesis")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Glory of the Liberation of Undermine Raider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Garbage In, Garbage Out")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Hold My Gear!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Just /Dance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\The Splash Zone")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Conveyor Slayer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Sleep with the Fishes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Scheming on a Thing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Exploration\\War Within\\C.H.E.T.T.mate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Slimy Yet Satisfying")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Sik Parry Bro")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Would You Still /love Me if I Was a Worm...")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Love is in the Lair")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\You Can't See Me")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Cowabunga")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Kill Streak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Missed 'Em by That Much")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Allied Races: Earthen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\The Grand Tapestry")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Exploration\\War Within\\Grand, Gutsy Solutions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Expansion Features\\Skyriding\\Undermine Breaknecking: Bronze")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Algari Dungeoneer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Damage Dealer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Healer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Tank")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Character Achievements\\Reputation\\The War Within Achievements\\Khaz Algar Diplomat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Sojourner of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Khaz Algar Lore Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Going Goblin Mode")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Adventurer of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Treasures of Undermine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Nine-Tenths of the Law")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\You're My Friend Now")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\That Can-Do Attitude")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Undermined")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\C.H.E.T.T. a Look")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Gobblin' with Glublurp")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\The War Within Achievements\\Flarendo's Biggest Fan")
