local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("AchievementsCBFA") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Battle of Dazar'alor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Eternal Palace")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Grand Reception")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Depths of the Devoted")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Circle of Stars")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Ny'alotha, the Waking City")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Vision of Destiny")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Halls of Devotion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle For Azeroth\\Gift of Flesh")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Waking Dream")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\I'm On Island Time")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Load of a Tale")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Hot Tropic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Sound Off")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Sailed in Sea Minor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Bwon Voyage")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Most Efficient Apocalypse")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Songs of Storms")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Dune Squad")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\When the Drust Settles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\War Stories")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Two Sides to Every Tale")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Corruptor's End")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Maximum Effort")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Frontline Warrior")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Undersea Usurper")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Mecha-Done")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Junkyard Machinist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Black Empire State of Mind")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Rajani")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Uldum Accord")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Combating the Corruption")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\It's Not A Tumor!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\All Consuming")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Defend the Vale")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Uldum Under Assault")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Full Heart, Can't Lose")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Heart Forge")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Power Is Beautiful")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\My Heart Container is Full")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Dressed to Kill: Battle for Azeroth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Under the Seams")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Never Lose, Never Choose To")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\All Eyes On Me")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Eyes Have It")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Farewell to Arms")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Uldir")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Halls of Containment")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Crimson Descent")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Heart of Corruption")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Battle of Dazar'alor")
