local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("EventsC") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Eversong Woods Void Assaults")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Zul'Aman Void Assaults")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Eversong Woods Ritual Site")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Zul'Aman Ritual Site")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Abyss Anglers")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Azerothian Archives!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Big Dig: Traitor's Rest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Thaldraszus)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Waking Shores)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Ohn'ahran Plains)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Azure Span)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Community Rumors")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth Mimiron's Jumpjets Mount")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Emerald Dream Superbloom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Incognitro, the Indecipherable Felcycle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Revisited Horrific Vision of Orgrimmar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Revisited Horrific Vision of Stormwind")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Nightfall")
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Pathfinder")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\The Drain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\The Drowned Lair")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\Shuddering Hollow")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\21st Anniversary Event Weeklies")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Guest Relations")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\No Crate Left Behind")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\I Saved the Party and All I got Were These Lousy Hats")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Assistant to the Assistant Guest Relations Manager")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Peanut Gallery")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Pet Mischief")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Balloonist")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\An Original")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Codex Editor: Ahn'Qiraj")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Classy Dresser")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Frequent Flyer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Mount Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Azeroth's Greatest Detective")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Fashion Critic")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Big Fan")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Avid Listener")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Photo Op!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\The Gatecrashers")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Zoomies!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\The Originals")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\I Have That One!")
ZygorGuidesViewer:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\A Gatecrasher")
