local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("DailiesCSHADOW") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Ardenweald World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Bastion World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Maldraxxus World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\The Maw World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Revendreth World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Zereth Mortis World Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Ve'nari Daily Quests (The Maw)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Kyrian Covenant\\Kyrian Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Necrolords Covenant\\Necrolord Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Night Fae Covenant\\Night Fae Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Night Fae Covenant\\Fungal Terminus Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Venthyr Covenant\\Venthyr Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Kyrian Covenant\\Kyrian Anima Conductor Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Necrolords Covenant\\Necrolords Anima Conductor Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Night Fae Covenant\\Night Fae Anima Conductor Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Venthyr Covenant\\Venthyr Anima Conductor Daily Quests")
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Necrolords Covenant\\Necrolords Abomination Factory Weekly Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Night Fae Covenant\\Night Fae Queen's Conservatory Daily Quests")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Chains of Domination\\Korthia Daily Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Daily Guides\\Shadowlands (50-70)\\Eternity's End\\Zereth Mortis Daily Quests")
