local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dungeon_Dragonflight_60-70_Uldaman_Legacy_of_Tyr")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cffffd200Dragonflight|r", "2071(25-70)", nil, nil, nil, "I", nil, function()
return [[

R Uldaman: Legacy of Tyr |N|Queue or Zone into (map:2071) (78.05,40.89)| |Z|2071| |F|2071 1| |I|
K The Lost Dwarves  |N|Kill (npc:184580), (npc:184582) and (npc:184581) (78.23,85.37)<br/><br/>Pay attention to (npc:184580)'s (spell:369677). It targets a random player and deals physical damage. It will ricochet to up to 5 players with in 5 yards, keep spread out at all times.<br/>(npc:184582) will occasionally cast (spell:369791), inflicting physical damage to players within 5 yards. Spread out to avoid the ground animation at all costs.<br/>Interrupt (spell:369603) from (npc:184580), it provides 75% damage reduction for the remaining Dwarves. It is important to note that during the entire duration of the (spell:369603).<br/>Once the Dwarves reach low health, they will hop on (spell:375924), and fire (spell:375286) at every alive member of your team at their current location. You must be stacked at this point and move slowly together to "save" space as the (spell:375286) will keep on going until the boss is defeated.<br/>At last, focusing on one boss at a time is going to be beneficial, as (spell:375398) will increase the rate at which (spell:375286) is firing, and the more Dwarves the are, the more frequently it will cast. This effect can snowball, especially on Mythic where (spell:395647) and (spell:377825) must be taken into consideration.<br/><br/>Tank: Use mitigation when (npc:184581) is casting (spell:369563). In addition, the ability "cleaves" any players in front of him within 10 yards, so it is important to face him away from your party to avoid casualties.<br/>Throughout the whole fight, you will also need to pay attention to (npc:184581)'s (spell:369573). It fires in a straight line (can't be interrupted), damaging the players and knocking them back upon inflicting damage. It always goes where you are facing the boss, keep it away from your party to avoid unnecessary deaths.<br/><br/>Healer: Beware of (npc:184582), he will cast (spell:369781) at a random player (can't be interrupted), and top them up quickly.| |Z|2071| |NPC|184580, 184582, 184581|
K (npc:184018) |SID||2| |N|Kill (npc:184018) (59.35,63.91)<br/><br/>Few seconds into the fight (npc:184018) will cast (spell:369605), summoning (npc:186658) and (npc:186664) (the same mobs that you have previously fought to get to the boss). It is important to note that because (npc:186658) is a caster, they will stay far away while casting spells on you. The best way to deal with them is to line of sight them so they can come close to the tank, or use interrupt/knock back abilities so you can "lock" them on the cast and make them move closer to you.<br/>Occasionally, the boss will cast (spell:369703), move out of the ground effect as quickly as you can.<br/>When (npc:184018) casts (spell:382303), you have to instantly shift your focus to it and kill it. While the (spell:382303) is active, the entire group will take (spell:369610) damage, so it's extremely important to nuke it quickly. Upon destroying the (spell:382303), it will cause (spell:396660) to stun all nearby Stonevault Troggs and increase their damage taken by 200% for 10 seconds.<br/>Pay attention when (spell:369754) is cast, you won't be able to interrupt it, but you can Enrage Dispel as soon as you see it. Stunning him during the cast with (spell:369660) will also stop the effect.<br/><br/>Tank: As soon as (spell:369605) has been cast, collect the aggro from the nearby (npc:186664) and (npc:186658).<br/><br/>Healer: Top up the group when they get damaged by the Stonevault Troggs.<br/>Use healing cool downs when the (spell:382303) appears; the group will take massive damage from (spell:369610) the longer the totem stays alive.| |Z|2071| |NPC|184018|
K (npc:184124) |SID||3| |N|Kill (npc:184124) (30.47,70.58)<br/><br/>Occasionally, (npc:184124) will cast (spell:372701), knocking players away, interrupting their casts and also during physical damage to all of them. Stop your cast at the end to prevent being locked.<br/>Avoid soaking any (spell:372623), this will significantly increase the difficulty of the fight.<br/><br/>Tank: The boss will cast (spell:372719) once she reaches 100 energy. It is important for you to clear her remaining stacks of (spell:372600) with the (spell:372623) before she reaches close to 100 energy, so later on you can stun her with the last (spell:372623) on the (spell:372719) cast preventing her from empowering.<br/><br/>Healer: When (npc:184124) casts (spell:372701), be prepared to top up the group quickly.<br/>Use your cool downs when the (spell:372718) bleed effect is going out (it will cast on random group members), this is good time to suggest that your teammates to use their personal defensive abilities. There are several spells that can completely mitigate the (spell:372701) effect, including (spell:20594) racial, Paladin's (spell:1022) or any other immunity.| |NPC|184124|
K (npc:184422) |SID||4| |N|Kill (npc:184422) (21.31,25.58)<br/><br/>Periodically, (npc:184422) will also cast (spell:369110) on a random player, it is extremely important to be spread out and never overlap each other with the surrounding circle. This is a great place to use your personal defensive abilities.<br/>The boss enters it's phase once he reaches maximum energy. During ths phase, he will have a (spell:369031) aura, preventing you from damaging him (beware not to stay in the middle where the boss is because you risk being hit by (spell:369029)). The phase will end once you defeat the 4 keepers, but the tricky part is, every 3 seconds other phase, the boss will cast (spell:369025). You can assign each keeper to a specific group member so you can defeat them faster.<br/>(spell:369990) will be present during the intermission phase, needless to say that it will probably turn lethal if you cross it, unless you have immunity, don't risk going through. The teleport effect will completely ignore the beams - Mage's (spell:212653) for example.<br/><br/>Aim the (spell:369061) frontal away from your group.<br/><br/>Healers: Be ready to dispel the (spell:369006) DoT effect immediately.<br/>During the (spell:369033) phase, use your healing cool downs to heal the group, as they will be taking constant (spell:369025) damage, during the entire phase.| |Z|2071| |NPC|184422|
K (npc:184125) |SID||5| |N|Kill (npc:184125) (40.24,26.42)<br/><br/>Periodically (npc:184125) will cast (spell:376292), do your best to dodge the ground animation and the followup pool of (spell:376325).<br/>Beware of (spell:376049), as it will not only interrupt your cast but it will knock you back, causing you to take physical damage. Make sure there is no (spell:376325) left behind you to avoid further damage.<br/><br/>Tank: (spell:375727) must be tanked away from the group, as it is a frontal cone ability that targets only you until the cast is finished.<br/><br/>Healer: Use healing cool downs when (spell:376208) begins, it will damage your group every 1 second for 12 seconds.| |Z|2072| |NPC|184125|
K (npc:184125) |QID|66868.1| |N|Kill (npc:184125) and collect (item:193409) (40.24,26.42)| |Z|2072| |NPC|184125| |O|

N Guide Complete

]]
end)
    end

    function Guide:Unload()
    end
end