local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dungeon_Dragonflight_60-70_The_Azure_Vault")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cffffd200Dragonflight|r", "2073(35-70)", nil, nil, nil, "I", nil, function()
return [[

N The Azure Vault |N|Queue or Zone into (map:2073) (75.61,33.29)| |Z|2073| |F|2073| |I|
K (npc:186644) |SID||1| |N|Kill (npc:186644) (37.11,54.16)<br/><br/><br/>(spell:374364) are periodically spawned throughout the fight by (npc:186644). These must be destroyed using the other abilities throughout the fight, or your group will wipe to the group wide damage done by (spell:374720). When you destroy (spell:374364), it spawns a (npc:191313), the same Oozelings you fought before the boss was activated.<br/>(spell:374567) is a knock back done by (npc:186644) which leaves a circle on everyone in the group. When this circle expires, it will destroy any (spell:374364) inside of it.<br/>(spell:374720) is a group wide damaging ability that will deal damage based on how many (spell:374364) are still alive in the room.<br/><br/>Tank: (spell:386660) is a frontal cone that is targeted on the tank. Once it starts casting, the boss will not turn. This needs to be aimed at as many (spell:374364) as possible, as it will destroy them.| |NPC|186644| |Z|2073|
K (npc:186739) |SID||2| |N|Kill (npc:186739) (76.09,55.67)<br/><br/><br/>(spell:384223) summons dragonkin around the room. This will shoot (spell:373932) at random group members and it must be interrupted. These should be dealt with as they spawn.<br/>(spell:385578) shoots an orb from the boss in a straight line to the edge of the room in any direction it chooses. You should dodge this as soon as it starts the channel.<br/>(spell:384132) causes the boss to run to the center. It will spawn four (npc:190187) which channel on the boss, making it immune to damage. You must kill the four images to continue the boss fight. While this is going on, the boss is also spawning 5 (spell:385578) at a time in a pentagon pattern and shooting them to the edges of the room. These must be dodged the same as the big ones during the main phase of the fight.<br/><br/>Tank: (spell:372222) is a frontal cone cleave. Don't aim this at the group.<br/><br/>Healer: Pay special attention during (spell:384132), as this causes a lot of unavoidable group damage and can quickly get out of control if you fall behind, leading to a wipe.| |Z|2075| |NPC|186739|
K (npc:199614) |SID||3| |N|Kill (npc:199614) (35.56,52.73)<br/><br/><br/>(spell:386910) is a debuff placed on the entire group. It drops a patch of ice on the ground, indicated by the circle around the player. These will then grow over the next 2 minutes, meaning the group must be conscious of their space they use. These can be dropped off the platform by players who have an ability to get back onto the platform.<br/>(spell:388008) will cause the boss to teleport to the center of the room and begin a channel. The group must make their way to the safety of a (spell:388072) somewhere on the floor, indicating by a blue bubble.<br/><br/>Healer: (spell:387151) is a targeted ability on a random group member that deals a large amount of damage and cleaves around them. This person will need extra focus.<br/>(spell:388008) will hit your group extremely hard. You should ensure everyone is topped up, or use something on anyone that you can't top before the detonation.| |Z|2076| |NPC|199614|
K (npc:186738) |SID||4| |N|Kill (npc:186738) (52.18,52.62)<br/><br/><br/>(spell:388777) is the main mechanic of the fight. It is a stacking slow that ramps up to 50% in total. Players gain a stack everytime they move, and should try to avoid getting stacks whenever possible by standing still.<br/>(spell:384699) is a frontal that is targeted at a random player.<br/>(spell:385399) is a large amount of group wide damage that comes out somewhat frequently. It should be mitigated when possible.<br/>(npc:195138)'s are spawned randomly by the boss, which must be killed before they finish their (spell:385331) cast, which leaves a massive DoT on the entire group if it goes off. It is practically unhealable, so do not let any explode.<br/>(spell:385075) happens whenever the boss reaches 100 energy. It causes (spell:385267) to spawn around the room, which slowly move towards players that can generate healing aggro.<br/><br/>Tank: (spell:384978) is a large amount of tank damage that should be mitigated.<br/><br/>Healer: (spell:385399) will hit your group very hard. You should make an effort to make sure everyone is topped up before it goes off.<br/>The (spell:385267) spawned by (spell:385075) will typically hunt you down, as you will be generating the most healing threat. As such, you should try to make big movements to get away from them whenever your slow drops, then plant until it clears again. You will have to be very conscious of your movement choices throughout this fight.| |Z|2077| |NPC|186738|
K (npc:186738) |QID|71155.1| |N|Kill (npc:186738) (52.18,52.62)| |Z|2077| |NPC|186738| |O|

N Guide Complete

]]
end)
	end

	function Guide:Unload()
	end
end
