local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dungeon_Dragonflight_60-70_Neltharus")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cffffd200Dragonflight|r", "2080(15-70)", nil, nil, nil, "I", nil, function()
return [[

N Neltharus |N|Queue or Zone into (map:2080) (52.37,22.96)| |Z|2080| |F|2080| |I|
K (npc:181861) |SID|| |N|Kill (npc:181861) (66.89,63.41)<br/><br/>(spell:374410) is the main mechanic of the fight. The longer it goes on, the more tentacles the boss will spawn (One for each time he reaches 100 energy). This empowers the other mechanics of the fight.<br/>(spell:375068) spawns a swirl on the ground that leaves behind a puddle of lava. If you hold the boss in the lave, he will deal 50% additional damage.<br/>(spell:375251) targets a random player in the party and does a wide cone on them.<br/>(spell:375439) will occasionally happen, causing the boss to charge towards a wall in the room. He also spawns lava waves for every tentacle when he reaches his destination, which fire out across the room from him to a wall.<br/><br/>Tank: You should pay special attention to the position of the boss, trying to keep it out of lava to avoid (spell:375068) and away from walls so the group has time to prepare for the charge and to dodge the cones.<br/><br/>Healer: (spell:375890) is the main healer mechanic. Fo each magma tentacle, the DoT that this spell leaves wil become stronger. Healers should plan their cool downs.| |NPC|181861| |Z|2080|
K (npc:189340) |SID|| |N|Kill (npc:189340) (43.17,66.70)<br/><br/>(spell:373424) is the main mechanic of the fight. The boss will target 3 players and chain them to the floor, causing them to be slowed by 40% and causing a puddle of lava to form at the location. Players need to step away fromt he spear that's chaining them and create a tripwire for the tank to kite the boss through. Once the boss trips three times, he will be stunned and take increased damage.<br/>(spell:375056) causes the boss to fixate the tank and swing wildly at him, causing lava pools to spawn randomly around the room and dealing damage to anyone within 6 yards of him. The tank must kite the boss through the chains that other players create from (spell:373424) to stop the fixate. For each chain the boss runs through, it will apply a stacking DoT to the group. Be aware of when the tank is coming towards you that you don't get close to the boss.<br/>(spell:373767) causes lava waves to spawn from the boss in a random direction.<br/><br/>Tank: (spell:375056) causes the boss to fixate you and swing wildly, causing lava pools to spawn randomly around the room and dealing damage to anyone within 6 yards of him. For each chain the boss runs through, it will apply a stacking DoT to the group, so be considerate of your healer and try not to stack the DoT.<br/<br/>(spell:373733) deals damage to a random party player and leaves a bleed on them. Pay attention to this target while they're bleeding.<br/>(spell:375056) causes the boss to fixate the tank and swing wildly at him, causing lava pools to spawn randomly around the room and dealing damage to anyone within 6 yards of him. For each chain the boss runs through during the fixate, it will apply a stacking DoT to the group. Be ready to heal a lot this phase, on your tank and your melee especially, but on the entire group as well.| |NPC|189340| |Z|2080| --54031
K (npc:189478) |SID|| |N|Kill (npc:189478) (33.73,65.69)<br/><br/>(spell:374594) causes the boss to return to his anvil and is the main mechanic of the fight. When he hammers, he will deal group wide damage. When he finishes crafting with his hammer, he will throw a (spell:374812) at a random player, causing a large X of orange swirls to spawn from the location, which must be dodged. The Aegis will then bounce to 2 additional players, causing two additional sets of swirls to spawn.<br/>(spell:375244) causes swirls to spawn randomly around the room, which you should dodge.<br/><br/>Tank: (spell:374535) is the tank combo of this fight, which will knock you back and leap on you, dealing a lot of damage. You should try to mitigate this in some capacity.<br/><br/>Healer: (spell:374640) is the main mechanic of this fight, which occurs everytime he strikes his anvil during (spell:374594). You should be prepared to do a lot of healing during this phase, as well as dodge the circles after the fact.| |NPC|189478| |Z|2081|
K (npc:189901) |SID|| |N|Kill (npc:189901) (52.09,86.95)<br/><br/>(spell:376780) is the main mechanic of the fight. Every so often, the boss will shield herself, and players must break the shield by digging through the piles of gold around the room and collecting different items. These items deal large amounts of damage to the shield and help you break it faster. While the shield holds, fire is thrown around the room and must be dodged in addition to the group wide damage that is pulsing. When the shield breaks, it deals damage to the group and causes the boss to take 100% additional damage for a short period.<br>(spell:377477) causes a (spell:192464) to spawn, leaving a large puddle of lava when it spawns. These Embers will contain lava, it will drop another puddle. These mobs can be crowd controlled to conserve space in the room, as once their fixate ends they will disappear.<br/>(spell:377204) is a randomly aimed frontal cone that players must step out of.<br/><br/>Healer: Be prepared to heal a lot during (spell:376780), as the pulsing damage is quite high.<br/>(spell:377018) is a DoT that is randomly applied to a party member, dealing heavy damage.| |NPC|189901| |Z|2080|
N 12 (item:201264) |QID|72135.1| |N|Collect 12 (item:201264) from most mobs within (map:2080)| |L|201264 12| |O|
N 3 (item:201263) |QID|72135.2| |N|Collect 3 (item:201263) from most mobs within (map:2080)| |L|201263 3| |O|
N (item:201266) |QID|72135.3| |N|Kill (npc:189901) and collect (item:201266) (52.09,86.95)| |F|2080| |NPC|189901| |L|201266| |O|
N Wanted: Earthbound Primordial Core |QID|71001.1| |N|Click on (item:200200) on a pile of gold (43.53,81.43)| |F|2080| |L|200200| |O|

N Guide Complete

]]
end)
    end

    function Guide:Unload()
    end
end