local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("LevelingCMID") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\The War of Light and Shadow Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Midnight Intro & Campaign (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Eversong Woods (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Zul'Aman (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Harandar (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Arator's Journey (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Voidstorm (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Midnight Intro & Campaign (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Eversong Woods (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Zul'Aman (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Harandar (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Arator's Journey (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Voidstorm (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Delves: Season 1")
ZGV.BETASTART()
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Prey: Season 1")
ZGV.BETAEND()
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Abundance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Catalyst")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Item Upgrade Tutorial")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Nulling Nullaeus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Pet Wranglin'")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Crimson Rogue")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Great Vault")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Saltheril's Haven")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Ritual Site and Void Incursion Quest Guide")
