local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("LevelingCTWW") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Starter Guides\\Earthen Starter (10-11)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Allied Races\\Earthen Race Unlock")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Allied Races\\Earthen Exploration Leveling (10-71)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Intro & Isle of Dorn (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The Ringing Deeps (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Hallowfall (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Azj-Kahet (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Intro & Isle of Dorn (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\The Ringing Deeps (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Hallowfall (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Azj-Kahet (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The War Within Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\To Kill A Queen")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Skyriding Glyphs\\The War Within Skyriding Glyphs (All Zones)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Siren Isle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Lingering Shadows")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The Fate of the Kirin Tor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Prismatic Snapdragon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Undermine (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Undermine (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Rise of the Red Dawn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Lorewalking")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\K'aresh (Story Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\K'aresh (Full Zone)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Ecological Succession")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Visions of a Shadowed Sun")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Lorewalking Recap")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Catch Up")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\The Cult Within")
