local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("LevelingHCATA") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Eversong Woods (1-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Ghostlands (1-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Silverpine Forest (5-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Hillsbrad Foothills (7-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Arathi Highlands (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Northern Stranglethorn (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\The Cape of Stranglethorn (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\The Hinterlands (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Western Plaguelands (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Badlands (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Blasted Lands (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Burning Steppes (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Eastern Plaguelands (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Searing Gorge (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Eastern Kingdoms\\Swamp of Sorrows (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Durotar (1-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Mulgore (1-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Northern Barrens (5-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Azshara (5-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Ashenvale (7-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Stonetalon Mountains (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Southern Barrens (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Desolace (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Dustwallow Marsh (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Feralas (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Felwood (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Silithus (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Tanaris (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Thousand Needles (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Un'Goro Crater (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Classic (1-70)\\Kalimdor\\Winterspring (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Hellfire Peninsula (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Zangarmarsh (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Terokkar Forest (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Nagrand (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Blade's Edge Mountains (20-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Netherstorm (25-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Burning Crusade (10-70)\\Shadowmoon Valley (25-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Borean Tundra (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Howling Fjord (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Dragonblight (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Grizzly Hills (15-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Zul'Drak (20-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Sholazar Basin (20-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\Icecrown (25-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Wrath of the Lich King (10-70)\\The Storm Peaks (25-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Cataclysm (10-70)\\Mount Hyjal (30-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Cataclysm (10-70)\\Vashj'ir (30-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Cataclysm (10-70)\\Deepholm (30-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Cataclysm (10-70)\\Uldum (30-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Cataclysm (10-70)\\Twilight Highlands (30-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Loremaster\\Loremaster of Eastern Kingdoms")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Loremaster\\Loremaster of Kalimdor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Loremaster\\Loremaster of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Loremaster\\Loremaster of Northrend")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\The Loremaster\\Loremaster of Cataclysm")
