local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("LevelingHBFA") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Zuldazar (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Nazmir (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Vol'dun (10-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Mechagon Island")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Nazjatar\\Nazjatar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Nazjatar\\Kelya's Grave")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Nazjatar\\Nazjatar Dropped Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\War Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Arathi Highlands Warfront Extra Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Darkshore Warfront Extra Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Warfronts Introduction Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Advanced Adventurer Augment")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Annoy-o-Tron Gang")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Anti-Gravity Pack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Battle Box")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: BAWLD-371")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Beastbot Powerpack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Blue Spraybot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Canned Minnows")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Powerpack")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Repair Kit")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Rocket Chicken")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Encrypted Black Market Radio")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Experimental Adventurer Augment")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Extraordinary Adventurer Augment")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: G99.99 Landshark")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Green Spraybot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Holographic Digitalization Relay")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Hundred-Fathom Lure")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Mechano-Treat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Mechanocat Laser Pointer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Microbot XD")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Orange Spraybot")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Perfectly Timed Differential")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Personal Time Displacer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Protocol Transference Device")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Re-Procedurally Generated Punchcard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Gramophone")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Kegerator")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Pocket Turret")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Resistance Insignia")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Requisitions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrap Grenade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrap Trap")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrapmaster's Blowtorch")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: S.P.A.R.E. Crate")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Ultrasafe Transporter - Mechagon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Utility Mechanoclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Vaultbot Key")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Swiftwind Post (Drustvar)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Wolf's Den (Tiragarde Sound)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Hillcrest Pasture (Stormsong Valley)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Mudfisher Cove (Drustvar)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Stonefist Watch (Tiragarde Sound)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Stonetusk Watch (Stormsong Valley)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Windfall Cavern (Stormsong Valley)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Heart of Azeroth\\Essential Empowerment")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Zuldazar Loremaster (Story Quest Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Nazmir Loremaster (Story Quest Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Zandalar\\Vol'dun Loremaster (Story Quest Only)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Mysterious Letter Questline")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Xal'atath's Gambit")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Xal'atath's Gambit - Priest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Hati's Sacrifice")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Before the Storm Questline")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Horrific Vision of Stormwind")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Horrific Vision of Orgrimmar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Heart of Azeroth\\Magni's Plan")
